import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case chinese = "zh-Hans"
    case english = "en"

    var id: String { rawValue }

    var locale: Locale { Locale(identifier: rawValue) }

    var nativeName: String {
        switch self {
        case .chinese: "中文"
        case .english: "English"
        }
    }

    static var systemDefault: AppLanguage {
        AppRegion.isMainlandChina ? .chinese : .english
    }
}

enum AppLanguageStore {
    private static let key = "app.language"

    static func load() -> AppLanguage {
        if let raw = UserDefaults.standard.string(forKey: key),
           let language = AppLanguage(rawValue: raw) {
            return language
        }
        return .systemDefault
    }

    static func save(_ language: AppLanguage) {
        UserDefaults.standard.set(language.rawValue, forKey: key)
    }
}

enum L10n {
    static var language: AppLanguage = AppLanguageStore.load()

    static func t(_ key: String, _ args: CVarArg...) -> String {
        t(key, language: language, arguments: args)
    }

    static func t(_ key: String, language: AppLanguage, arguments: [CVarArg] = []) -> String {
        let template = table[language]?[key] ?? table[.chinese]?[key] ?? key
        guard !arguments.isEmpty else { return template }
        return String(format: template, locale: language.locale, arguments: arguments)
    }

    private static let table: [AppLanguage: [String: String]] = [
        .chinese: [
            "tab.home": "首页",
            "tab.devices": "设备",
            "tab.account": "我的",
            "common.back": "返回",
            "common.cancel": "取消",
            "common.close": "关闭",
            "common.done": "完成",
            "common.alert": "提示",
            "common.ok": "知道了",
            "common.user": "用户",
            "project.home": "首页",
            "project.composition": "成分分析",
            "project.coming_soon": "敬请期待",
            "discovery.title": "发现设备",
            "discovery.empty": "附近没有设备",
            "discovery.empty_hint": "请打开 NIR 或 IR2210 设备并保持在附近",
            "discovery.rescan": "重新扫描",
            "discovery.scanning": "正在扫描附近设备…",
            "discovery.bind_title": "绑定这台设备？",
            "discovery.bind_continue": "绑定并继续",
            "discovery.bind_message": "设备尚未激活，将绑定到当前账号。",
            "mode.title": "选择分析模式",
            "mode.monthly_use": "本月已使用 %d 次",
            "workbench.inspect": "检测",
            "workbench.disconnected": "未连接设备",
            "workbench.connected": "已连接",
            "workbench.settings": "检测设置",
            "workbench.scan_mode": "扫描方式",
            "workbench.calibration": "校准方式",
            "workbench.start_manual_cal": "开始手动校准",
            "workbench.collected": "已采集 %d / 9 次",
            "workbench.scan_and_predict": "将完成扫描并立即预测",
            "workbench.hardware_hint": "也可按设备实体扫描键",
            "workbench.start_scan": "开始扫描",
            "workbench.predict_n": "对 %d 次采集进行预测",
            "workbench.clear": "清空已采集数据",
            "workbench.result": "分析结果",
            "workbench.result_based": "结果基于 %d 次采集",
            "workbench.more": "更多操作",
            "workbench.save_spectrum": "保存谱线与多点数据",
            "workbench.save_pending": "保存功能将在真实预测接口接入后启用",
            "workbench.ir_config": "IR2210 设备配置",
            "scan.single": "单次扫描",
            "scan.multiple": "多次扫描",
            "cal.builtin": "默认校准",
            "cal.manual": "手动校准",
            "device.settings.title": "设备配置",
            "device.settings.params": "采集参数",
            "device.settings.integration": "积分时间",
            "device.settings.instant": "即测即亮",
            "device.settings.average": "多次均值",
            "device.settings.average_count": "均值次数：%d",
            "device.settings.cal": "校准",
            "device.settings.ti": "TI 默认参考",
            "device.settings.aopu": "奥普默认参考",
            "device.settings.dark": "暗电流校准",
            "device.settings.save": "保存配置",
            "devices.title": "我的设备",
            "devices.empty": "还没有绑定设备",
            "devices.empty_hint": "在首页连接设备后即可完成绑定",
            "devices.detail": "设备详情",
            "devices.monthly_count": "本月使用次数",
            "devices.trend": "使用趋势",
            "devices.month": "月份",
            "devices.count": "次数",
            "devices.manage_share": "管理设备分享",
            "share.title": "设备分享",
            "share.add": "添加共享用户",
            "share.phone": "用户手机号",
            "share.action": "分享设备",
            "share.existing": "已共享",
            "share.empty": "尚未分享给其他用户",
            "share.revoke": "取消",
            "account.title": "我的",
            "account.permissions": "权限",
            "account.admin_level": "管理员等级",
            "account.sign_out": "退出登录",
            "account.language": "语言",
            "auth.tagline": "连接近红外设备，快速获取可信的分析数据",
            "auth.region_cn": "当前地区：中国大陆",
            "auth.region_intl": "当前地区：国际",
            "auth.login_title": "用户登录",
            "auth.register_title": "创建账号",
            "auth.username": "用户名",
            "auth.account_cn": "手机号或邮箱",
            "auth.account_intl": "邮箱",
            "auth.password": "密码（至少 6 位）",
            "auth.confirm_password": "确认密码",
            "auth.code": "验证码",
            "auth.get_code": "获取验证码",
            "auth.company": "公司（选填）",
            "auth.industry": "所在行业",
            "auth.login": "登录",
            "auth.register": "注册并登录",
            "auth.to_register": "没有账号？点击注册",
            "auth.to_login": "已有账号？点击登录",
            "auth.privacy": "登录即表示同意用户协议和隐私政策。账号将保存在本机，下次打开自动登录。",
            "industry.research": "科研人员",
            "industry.inspection": "检测人员",
            "industry.manufacturer": "生产商",
            "industry.personal": "个人自用",
            "industry.trade": "贸易行业",
            "busy.processing": "正在处理",
            "busy.logging_in": "正在登录",
            "busy.sending_code": "正在发送验证码",
            "busy.registering": "正在注册",
            "busy.scanning": "扫描中，请勿移动设备",
            "busy.predicting": "正在预测",
            "busy.processing_data": "处理数据中",
            "notice.bind_ok": "设备绑定成功",
            "notice.cal_ok": "手动校准完成",
            "notice.shared": "设备已分享",
            "error.invalid_phone": "请输入正确的 11 位手机号",
            "error.invalid_email": "请输入正确的邮箱",
            "error.invalid_password": "请输入至少 6 位密码",
            "error.unauthorized": "登录已过期，请重新登录",
            "error.invalid_code": "请输入验证码",
            "error.username": "请输入用户名",
            "error.password_mismatch": "两次输入的密码不一致",
            "error.max_scans": "多次扫描最多保存 9 次",
            "error.min_scans": "多次预测至少需要完成 2 次扫描",
            "error.hardware_busy": "当前任务尚未完成，请稍后再按设备扫描键",
            "error.login_failed": "登录失败",
            "error.code_failed": "验证码发送失败",
            "error.register_failed": "注册失败",
            "error.invalid_response": "服务器响应无效",
            "error.http": "接口请求失败（HTTP %d）",
            "error.decode": "服务器返回数据格式不正确",
            "error.decode_detail": "服务器返回数据格式不正确：%@",
            "error.missing_token": "登录成功但未返回 token",
            "error.device_info": "获取设备信息失败",
            "error.device_unavailable": "设备当前不可用",
            "error.bind_failed": "设备绑定失败",
            "error.device_list": "获取设备列表失败",
            "error.shared_users": "获取共享用户失败",
            "error.share_failed": "分享设备失败",
            "error.revoke_failed": "取消分享失败",
            "error.invalid_url": "接口地址无效",
            "error.http_500": "服务器内部错误（HTTP %d），请联系后台管理员",
            "error.connect": "无法连接服务器：%@",
            "error.login_http": "接口请求失败（HTTP %d）",
            "pred.invalid_response": "服务器返回了无法识别的数据",
            "pred.invalid_builtin": "NIR 内置参考必须是长度为 3822 的原始字节流",
            "pred.need_nir": "请先采集 NIR 光谱",
            "pred.nir_length": "每次 NIR 扫描必须包含 3822 个字节",
            "pred.nir_range": "NIR 扫描数据必须是 0–255 的整数",
            "pred.need_ir": "请先采集 IR2210 光谱",
            "pred.ir_length": "每次 IR2210 扫描必须包含 256 个强度值",
            "pred.failed": "预测失败",
            "pred.ref_failed": "设置参考光谱失败",
            "bt.checking": "正在检查蓝牙",
            "bt.ready": "蓝牙已就绪",
            "bt.off": "蓝牙已关闭",
            "bt.unauthorized": "请在系统设置中允许蓝牙访问",
            "bt.unsupported": "此设备不支持蓝牙",
            "bt.not_ready": "蓝牙尚未就绪",
            "bt.device_lost": "设备连接已断开",
            "bt.missing_char": "设备缺少必要特征：%@",
            "bt.timeout": "%@超时，请重试",
            "bt.connection_failed": "连接失败：%@",
            "bt.busy_connect": "已有连接正在进行",
            "bt.busy_scan": "已有扫描正在进行",
            "bt.busy_other": "设备正在执行其他操作",
            "bt.unknown": "未知原因",
            "bt.disconnected": "设备已断开",
            "bt.no_service": "未发现设备服务",
            "bt.op.connect": "连接设备",
            "bt.op.read_sn": "读取设备编号",
            "bt.op.builtin": "读取内置参考",
            "bt.op.nir_scan": "NIR 扫描",
            "bt.op.nir_data": "读取 NIR 扫描数据",
            "bt.op.ir_scan": "IR2210 扫描",
            "bt.ir_no_builtin": "IR2210 不使用 NIR 内置参考",
            "bt.nir_builtin_len": "NIR 内置参考长度为 %d，应为 3822",
            "bt.nir_scan_len": "NIR 光谱长度为 %d，应为 3822",
            "bt.ir_incomplete": "IR2210 光谱分包不完整",
            "bt.ir_empty_sn": "IR2210 序列号为空",
            "a11y.signal": "信号强度 %d 格"
        ],
        .english: [
            "tab.home": "Home",
            "tab.devices": "Devices",
            "tab.account": "Me",
            "common.back": "Back",
            "common.cancel": "Cancel",
            "common.close": "Close",
            "common.done": "Done",
            "common.alert": "Notice",
            "common.ok": "OK",
            "common.user": "User",
            "project.home": "Home",
            "project.composition": "Composition",
            "project.coming_soon": "Coming soon",
            "discovery.title": "Find Devices",
            "discovery.empty": "No nearby devices",
            "discovery.empty_hint": "Turn on an NIR or IR2210 device and keep it nearby",
            "discovery.rescan": "Scan again",
            "discovery.scanning": "Scanning nearby devices…",
            "discovery.bind_title": "Bind this device?",
            "discovery.bind_continue": "Bind and continue",
            "discovery.bind_message": "This device is not activated yet. It will be bound to the current account.",
            "mode.title": "Choose Analysis Mode",
            "mode.monthly_use": "Used %d times this month",
            "workbench.inspect": "Measure",
            "workbench.disconnected": "No device connected",
            "workbench.connected": "Connected",
            "workbench.settings": "Measurement settings",
            "workbench.scan_mode": "Scan mode",
            "workbench.calibration": "Calibration",
            "workbench.start_manual_cal": "Start manual calibration",
            "workbench.collected": "Collected %d / 9",
            "workbench.scan_and_predict": "Scan will run prediction immediately",
            "workbench.hardware_hint": "You can also press the device scan button",
            "workbench.start_scan": "Start scan",
            "workbench.predict_n": "Predict from %d scans",
            "workbench.clear": "Clear collected scans",
            "workbench.result": "Analysis result",
            "workbench.result_based": "Result based on %d scans",
            "workbench.more": "More actions",
            "workbench.save_spectrum": "Save spectrum and multi-point data",
            "workbench.save_pending": "Saving will be enabled after the live prediction API is connected",
            "workbench.ir_config": "IR2210 device settings",
            "scan.single": "Single scan",
            "scan.multiple": "Multiple scans",
            "cal.builtin": "Default calibration",
            "cal.manual": "Manual calibration",
            "device.settings.title": "Device Settings",
            "device.settings.params": "Acquisition",
            "device.settings.integration": "Integration time",
            "device.settings.instant": "Instant light",
            "device.settings.average": "Averaging",
            "device.settings.average_count": "Averages: %d",
            "device.settings.cal": "Calibration",
            "device.settings.ti": "TI default reference",
            "device.settings.aopu": "Aopu default reference",
            "device.settings.dark": "Dark current calibration",
            "device.settings.save": "Save settings",
            "devices.title": "My Devices",
            "devices.empty": "No bound devices",
            "devices.empty_hint": "Connect a device on Home to bind it",
            "devices.detail": "Device Details",
            "devices.monthly_count": "Uses this month",
            "devices.trend": "Usage trend",
            "devices.month": "Month",
            "devices.count": "Count",
            "devices.manage_share": "Manage sharing",
            "share.title": "Device Sharing",
            "share.add": "Add shared user",
            "share.phone": "User phone number",
            "share.action": "Share device",
            "share.existing": "Shared with",
            "share.empty": "Not shared with anyone yet",
            "share.revoke": "Remove",
            "account.title": "Me",
            "account.permissions": "Permissions",
            "account.admin_level": "Admin level",
            "account.sign_out": "Sign out",
            "account.language": "Language",
            "auth.tagline": "Connect near-infrared devices and get trusted analysis data quickly",
            "auth.region_cn": "Current region: Chinese mainland",
            "auth.region_intl": "Current region: International",
            "auth.login_title": "Sign in",
            "auth.register_title": "Create account",
            "auth.username": "Username",
            "auth.account_cn": "Phone number or email",
            "auth.account_intl": "Email",
            "auth.password": "Password (at least 6 characters)",
            "auth.confirm_password": "Confirm password",
            "auth.code": "Verification code",
            "auth.get_code": "Get code",
            "auth.company": "Company (optional)",
            "auth.industry": "Industry",
            "auth.login": "Sign in",
            "auth.register": "Register and sign in",
            "auth.to_register": "No account? Register",
            "auth.to_login": "Have an account? Sign in",
            "auth.privacy": "By signing in, you agree to the terms and privacy policy. Your account is saved on this device for automatic sign-in.",
            "industry.research": "Researcher",
            "industry.inspection": "Inspector",
            "industry.manufacturer": "Manufacturer",
            "industry.personal": "Personal use",
            "industry.trade": "Trade",
            "busy.processing": "Processing",
            "busy.logging_in": "Signing in",
            "busy.sending_code": "Sending code",
            "busy.registering": "Registering",
            "busy.scanning": "Scanning, keep the device still",
            "busy.predicting": "Predicting",
            "busy.processing_data": "Processing data",
            "notice.bind_ok": "Device bound",
            "notice.cal_ok": "Manual calibration complete",
            "notice.shared": "Device shared",
            "error.invalid_phone": "Enter a valid 11-digit phone number",
            "error.invalid_email": "Enter a valid email address",
            "error.invalid_password": "Enter a password with at least 6 characters",
            "error.unauthorized": "Session expired. Please sign in again",
            "error.invalid_code": "Enter the verification code",
            "error.username": "Enter a username",
            "error.password_mismatch": "Passwords do not match",
            "error.max_scans": "Multiple scan mode can save up to 9 scans",
            "error.min_scans": "Multiple-scan prediction needs at least 2 scans",
            "error.hardware_busy": "A task is still running. Press the device scan button later",
            "error.login_failed": "Sign-in failed",
            "error.code_failed": "Failed to send verification code",
            "error.register_failed": "Registration failed",
            "error.invalid_response": "Invalid server response",
            "error.http": "Request failed (HTTP %d)",
            "error.decode": "Unexpected server data format",
            "error.decode_detail": "Unexpected server data format: %@",
            "error.missing_token": "Signed in but no token was returned",
            "error.device_info": "Failed to load device info",
            "error.device_unavailable": "Device is currently unavailable",
            "error.bind_failed": "Failed to bind device",
            "error.device_list": "Failed to load device list",
            "error.shared_users": "Failed to load shared users",
            "error.share_failed": "Failed to share device",
            "error.revoke_failed": "Failed to remove sharing",
            "error.invalid_url": "Invalid API URL",
            "error.http_500": "Server error (HTTP %d). Please contact the administrator",
            "error.connect": "Unable to connect to the server: %@",
            "error.login_http": "Request failed (HTTP %d)",
            "pred.invalid_response": "The server returned unrecognized data",
            "pred.invalid_builtin": "NIR built-in reference must be a 3822-byte raw stream",
            "pred.need_nir": "Capture an NIR spectrum first",
            "pred.nir_length": "Each NIR scan must contain 3822 bytes",
            "pred.nir_range": "NIR scan values must be integers from 0 to 255",
            "pred.need_ir": "Capture an IR2210 spectrum first",
            "pred.ir_length": "Each IR2210 scan must contain 256 intensity values",
            "pred.failed": "Prediction failed",
            "pred.ref_failed": "Failed to set reference spectrum",
            "bt.checking": "Checking Bluetooth",
            "bt.ready": "Bluetooth is ready",
            "bt.off": "Bluetooth is off",
            "bt.unauthorized": "Allow Bluetooth access in Settings",
            "bt.unsupported": "This device does not support Bluetooth",
            "bt.not_ready": "Bluetooth is not ready",
            "bt.device_lost": "Device disconnected",
            "bt.missing_char": "Device is missing a required characteristic: %@",
            "bt.timeout": "%@ timed out. Please retry",
            "bt.connection_failed": "Connection failed: %@",
            "bt.busy_connect": "A connection is already in progress",
            "bt.busy_scan": "A scan is already in progress",
            "bt.busy_other": "The device is busy with another task",
            "bt.unknown": "Unknown reason",
            "bt.disconnected": "Device disconnected",
            "bt.no_service": "Device services not found",
            "bt.op.connect": "Connecting",
            "bt.op.read_sn": "Reading serial number",
            "bt.op.builtin": "Reading built-in reference",
            "bt.op.nir_scan": "NIR scan",
            "bt.op.nir_data": "Reading NIR scan data",
            "bt.op.ir_scan": "IR2210 scan",
            "bt.ir_no_builtin": "IR2210 does not use the NIR built-in reference",
            "bt.nir_builtin_len": "NIR built-in reference length is %d, expected 3822",
            "bt.nir_scan_len": "NIR spectrum length is %d, expected 3822",
            "bt.ir_incomplete": "IR2210 spectrum packets are incomplete",
            "bt.ir_empty_sn": "IR2210 serial number is empty",
            "a11y.signal": "Signal strength %d"
        ]
    ]
}
